=== leesunghyun-git/WebStudy/JSPBasicProject_3/src/main/webapp/xml/sawon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	<sawon>
		<list>
			<sabun></sabun>
			<name></name>
			<dept></dept>
			<phoen></phone>
			<address></address>
		</list>
		<list>
			<sabun></sabun>
			<name></name>
			<dept></dept>
			<phoen></phone>
			<address></address>
		</list>
	</sawon>
 -->
 <!ELEMENT sawon (list+)>
 <!ELEMENT list (sabun,name,dept,(phone|tell),address)>
 <!ELEMENT sabun (#PCDATA) >
 <!ELEMENT name (#PCDATA) >
 <!ELEMENT dept (#PCDATA) >
 <!ELEMENT phone (#PCDATA) >
 <!ELEMENT tell (#PCDATA) >
 <!ELEMENT address (#PCDATA) >
 <!ENTITY nbsp " "> <!-- &nbsp; -->
 <!ENTITY lt "<">
 <!ENTITY gt ">">
 <!ENTITY sawon "sawon.xml">

=== leesunghyun-git/WebStudy/JSPBasicProject_3/src/main/webapp/xml/sawon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sawon SYSTEM "sawon.dtd">
<sawon>
	<list>
		<sabun></sabun>
		<name></name>
		<dept></dept>
		<phone></phone>
		<address></address>
	</list>
	<list>
		<sabun></sabun>
		<name></name>
		<dept></dept>
		<tell></tell>
		<address></address>
	</list>
</sawon>
